import { compact, palette, type Card, type Theme } from '@/lib/types';
import type { CSSProperties } from 'react';
export function CardOG({ card, theme }: { card: Card; theme: Theme }) {
 const p = palette[theme]; const { profile, stars, languages } = card.data;
 const name = profile.name || profile.login;
 const flex: CSSProperties = { display: 'flex' };
 const column: CSSProperties = { display: 'flex', flexDirection: 'column' };
 const stats = [['Followers', profile.followers], ['Following', profile.following], ['Repos', profile.public_repos], ['Stars', stars]] as const;
 const avatar = (size: number, radius = 0) => <img src={profile.avatar_url} alt="" width={size} height={size} style={{ borderRadius: radius, border: `4px solid ${p.accent}` }}/>;
 const metrics = <div style={{ ...flex, gap: 16, marginTop: 24 }}>{stats.map(([label, value], i) => <div key={label} style={{ ...column, flex: 1, padding: 16, border: `${theme === 'superhero' ? 3 : 1}px solid ${p.border}`, borderRadius: theme === 'ai' ? 16 : 0, background: theme === 'superhero' ? '#fff9e9' : p.bg }}><span style={{ fontSize: 13, color: p.muted }}>0{i + 1} / {label.toUpperCase()}</span><span style={{ fontSize: 38, marginTop: 7, color: theme === 'superhero' ? p.text : p.accent }}>{compact(value)}</span></div>)}</div>;
 const stack = <div style={{ ...flex, gap: 18, marginTop: 23, fontSize: 17 }}>{languages.slice(0, 5).map(l => <span key={l.name} style={{ color: theme === 'anime' || theme === 'superhero' ? p.text : l.color }}>{l.name} · {Math.round(l.percent)}%</span>)}</div>;
 const title = <div style={{ ...column }}><span style={{ fontSize: name.length > 24 ? 36 : 48, fontWeight: 700 }}>{name}</span><span style={{ fontSize: 23, marginTop: 8, color: p.muted }}>@{profile.login}</span></div>;
 const description = <div style={{ ...flex, color: p.muted, fontSize: 21, lineHeight: 1.4, marginTop: 16 }}>{(profile.bio || 'Building in the open.').slice(0, 140)}</div>;
 return <div data-design={theme} style={{ ...column, width: 1200, height: 630, padding: theme === 'coder' || theme === 'linux' ? 0 : 32, background: p.bg, color: p.text, fontFamily: 'sans-serif', border: `3px solid ${p.border}` }}>
 {theme === 'anime' && <><div style={{ ...flex, justifyContent: 'space-between', borderBottom: `3px solid ${p.border}`, paddingBottom: 14 }}><span style={{ fontSize: 19 }}>DEVCARD / CHARACTER FILE</span><span style={{ background: p.accent, color: '#ffffff', padding: '5px 14px', fontSize: 18 }}>OPEN SOURCE PROTAGONIST</span></div><div style={{ ...flex, flex: 1, gap: 30, marginTop: 24 }}><div style={{ ...column, width: 265, background: '#f8cdd9', padding: 18, border: `3px solid ${p.border}`, alignItems: 'center', justifyContent: 'center', transform: 'rotate(-2deg)' }}>{avatar(204)}<span style={{ fontSize: 48, fontWeight: 700, marginTop: 14 }}>DEV / 01</span></div><div style={{ ...column, flex: 1, justifyContent: 'center' }}>{title}{description}{metrics}{stack}</div></div><span style={{ marginTop: 20, fontSize: 15 }}>THE NEXT ARC STARTS HERE / github.com/{profile.login}</span></>}
 {theme === 'ai' && <><div style={{ ...flex, justifyContent: 'space-between', fontSize: 20, color: p.accent }}><span>NEURAL PROFILE</span><span>NODE / {profile.id}</span></div><div style={{ ...flex, alignItems: 'center', gap: 45, padding: '32px 16px 0' }}><div style={{ ...flex, padding: 15, borderRadius: 130, border: '2px solid #555087', background: 'radial-gradient(circle, #343166, #0d1128)' }}>{avatar(170, 100)}</div><div style={{ ...column, flex: 1 }}>{title}{description}</div></div><div style={{ ...column, padding: '0 16px' }}>{metrics}{stack}</div><div style={{ ...flex, marginTop: 'auto', paddingTop: 22, borderTop: `1px solid ${p.border}`, justifyContent: 'space-between', fontSize: 16, color: p.muted }}><span>PUBLIC DATA / LANGUAGE VECTORS / PROJECT OUTPUTS</span><span>devcard</span></div></>}
 {theme === 'alien' && <><div style={{ ...flex, background: p.accent, color: p.bg, padding: '13px 18px', justifyContent: 'space-between', fontSize: 20 }}><span>EXTRATERRESTRIAL ARCHIVE</span><span>FILE {profile.id}</span></div><div style={{ ...flex, gap: 34, marginTop: 26 }}><div style={{ ...column, padding: 13, border: `2px dashed ${p.accent}`, alignItems: 'center' }}>{avatar(200)}<span style={{ marginTop: 13, fontSize: 17 }}>SPECIMEN / DEV</span></div><div style={{ ...column, flex: 1 }}><span style={{ fontSize: 15, color: p.accent, marginBottom: 14 }}>CLASSIFICATION: BUILDER</span>{title}<span style={{ marginTop: 16, fontSize: 18, color: p.muted }}>ORIGIN: {profile.location || 'UNDISCLOSED'}</span>{description}</div></div>{metrics}<div style={{ ...flex, justifyContent: 'space-between', alignItems: 'center' }}>{stack}<span style={{ fontSize: 15, marginTop: 22, color: p.accent }}>TRANSMISSION COMPLETE</span></div></>}
 {theme === 'superhero' && <><div style={{ ...flex, justifyContent: 'space-between', background: p.text, color: '#ffe448', padding: '10px 17px', fontSize: 21, fontWeight: 700 }}><span>THE INCREDIBLE DEVELOPER</span><span>ISSUE #{String(profile.id).slice(-3)}</span></div><div style={{ ...flex, gap: 30, alignItems: 'center', marginTop: 20 }}><div style={{ ...column, alignItems: 'center', background: p.accent, padding: 12, border: `4px solid ${p.border}`, transform: 'rotate(-3deg)' }}>{avatar(145)}<span style={{ color: '#ffffff', fontSize: 30, fontWeight: 700, marginTop: 4 }}>CODE!</span></div><div style={{ ...column, flex: 1 }}><span style={{ color: p.accent, fontSize: 18, marginBottom: 8 }}>MEET YOUR HERO</span>{title}<div style={{ ...flex, background: '#fff9e9', padding: '10px 18px', border: `3px solid ${p.border}`, marginTop: 16, fontSize: 18 }}>{(profile.bio || 'Building in the open.').slice(0, 120)}</div></div></div>{metrics}{stack}<span style={{ fontSize: 15, marginTop: 20 }}>DEVCARD COMICS / YOUR DEVELOPER ORIGIN STORY</span></>}
 {theme === 'coder' && <><div style={{ ...flex, background: '#222838', padding: '16px 25px', justifyContent: 'space-between', fontSize: 17, color: p.muted }}><span>● ● ●</span><span>{profile.login} — devcard</span><span>DEV</span></div><div style={{ ...flex, background: '#121620', height: 44 }}><span style={{ background: p.bg, color: '#80c9b3', padding: '10px 30px', fontSize: 18 }}>TS developer.ts</span><span style={{ padding: '10px 30px', fontSize: 18, color: p.muted }}>README.md</span></div><div style={{ ...flex, flex: 1 }}><div style={{ ...column, width: 60, background: '#202635', alignItems: 'center', paddingTop: 30, color: p.muted, fontSize: 23 }}>{'{ }'}</div><div style={{ ...column, padding: '24px 35px', flex: 1 }}><div style={{ ...flex, gap: 20, alignItems: 'center' }}>{avatar(80, 8)}{title}</div><div style={{ ...column, fontSize: 21, gap: 10, marginTop: 22 }}><span style={{ color: '#bf9def' }}>01　 export const developer = {'{'}</span><span style={{ color: '#80c9b3' }}>02　　 username: &quot;{profile.login}&quot;,</span><span style={{ color: '#80c9b3' }}>03　　 stack: [{languages.slice(0, 3).map(l => `"${l.name}"`).join(', ')}]</span><span style={{ color: '#bf9def' }}>04　 {'};'}</span></div>{metrics}</div></div><div style={{ ...flex, justifyContent: 'space-between', background: '#277265', padding: '8px 24px', fontSize: 16 }}><span>main*</span><span>TypeScript · UTF-8 · DevCard</span></div></>}
 {theme === 'linux' && <><div style={{ ...flex, background: '#3a293f', padding: '15px 24px', justifyContent: 'space-between', fontSize: 17 }}><span>● ● ●</span><span>{profile.login}@devcard: ~</span><span>- + x</span></div><div style={{ ...column, padding: '25px 40px' }}><span style={{ color: p.accent, fontSize: 22 }}>{profile.login}@devcard:~$ fastfetch --github</span><div style={{ ...flex, gap: 45, marginTop: 28 }}><div style={{ ...column, alignItems: 'center', paddingTop: 25 }}>{avatar(205, 6)}<span style={{ color: p.muted, fontSize: 17, marginTop: 15 }}>[ public profile ]</span></div><div style={{ ...column, flex: 1, gap: 8, fontSize: 21 }}><span style={{ color: p.accent, fontWeight: 700 }}>{profile.login}@github</span><span style={{ color: p.muted }}>--------------------------------</span>{[['Name', name], ['Host', 'GitHub'], ['Location', profile.location || 'Earth'], ...stats.map(([k, v]) => [k, compact(v)])].map(([key, value]) => <div key={key} style={{ ...flex, gap: 18 }}><span style={{ color: p.accent, width: 110 }}>{key}:</span><span>{value}</span></div>)}<div style={{ ...flex, marginTop: 10 }}>{['#eb6f92','#f6c177','#9ccfd8','#c4a7e7','#31748f','#ebbcba','#e0def4','#908caa'].map(color => <span key={color} style={{ background: color, width: 32, height: 24 }}/>)}</div></div></div><span style={{ color: p.accent, fontSize: 20, marginTop: 24 }}>&gt; cat about.txt</span><span style={{ color: p.text, fontSize: 19, marginTop: 10 }}>{(profile.bio || 'Building in the open.').slice(0, 120)}</span></div></>}
 </div>;
}
