import { palette, colors, compact, resolveTheme, type Card, type Theme } from '@/lib/types';
import type { CSSProperties } from 'react';
import { CardOG } from './card-og';

type Props = { data: Card; theme?: Theme; og?: boolean; miniature?: boolean };
export function DevCard({ data: card, theme = resolveTheme(card.theme), og = false, miniature = false }: Props) {
 const p = palette[theme]; const { profile, stars, repos, languages, activity } = card.data;
 const name = profile.name || profile.login;
 const stats = [['Followers', profile.followers], ['Following', profile.following], ['Repos', profile.public_repos], ['Stars', stars]] as const;
 if (og) return <CardOG card={card} theme={theme}/>;
 const avatar = <img className="design-avatar" src={profile.avatar_url} alt={miniature ? '' : `${name}'s avatar`} width={100} height={100} crossOrigin="anonymous"/>;
 const bio = <p className="design-bio">{profile.bio || 'Building in the open.'}</p>;
 const metrics = <div className="design-metrics">{stats.map(([label, value], index) => <div key={label}><span className="metric-index">0{index + 1}</span><strong>{compact(value)}</strong><span>{label}</span></div>)}</div>;
 const languageSection = <section className="design-languages"><h3>{theme === 'linux' ? '$ languages --usage' : theme === 'anime' ? 'SKILL TREE' : theme === 'superhero' ? 'SUPERPOWERS' : theme === 'alien' ? 'DECODED LANGUAGES' : theme === 'ai' ? 'LANGUAGE VECTORS' : 'stack.dependencies'}</h3><p className="language-source">{card.data.languageLabel || 'By code bytes · top repositories'}</p><div className="design-language-list">{languages.slice(0, 5).map(l => <div key={l.name}><span><i style={{ background: l.color }}/>{l.name}</span><div className="design-meter"><span style={{ width: `${l.percent}%`, background: theme === 'alien' ? p.accent : l.color }}/></div><em>{Math.round(l.percent)}%</em></div>)}{!languages.length && <p>No language data yet.</p>}</div></section>;
 const repoSection = <section className="design-repositories"><h3>{theme === 'anime' ? 'QUEST LOG' : theme === 'superhero' ? 'HEROIC ENDEAVORS' : theme === 'alien' ? 'RECOVERED ARTIFACTS' : theme === 'ai' ? 'PROJECT OUTPUTS' : theme === 'linux' ? '$ ls ~/projects' : 'EXPLORER / projects'}</h3><div className="design-repo-grid">{repos.map((r, i) => <a href={r.html_url} key={r.name} target="_blank" rel="noreferrer" className="design-repo"><span className="repo-number">{theme === 'linux' ? 'drwxr-xr-x' : theme === 'coder' ? 'TS' : `0${i + 1}`}</span><div><strong>{r.name}</strong><p>{r.description || 'An open-source project.'}</p></div><span className="repo-stars">☆ {compact(r.stargazers_count)}</span></a>)}{!repos.length && <p>The next project starts here.</p>}</div></section>;
 const activitySection = <section className="design-activity"><h3>{theme === 'linux' ? '$ git activity' : theme === 'alien' ? 'SIGNAL HISTORY' : theme === 'anime' ? 'TRAINING ARC' : theme === 'superhero' ? 'ON PATROL' : theme === 'coder' ? 'TERMINAL / activity' : 'ACTIVITY TELEMETRY'}<span>52 WEEKS</span></h3><div className="heatmap">{activity.map(day => <span key={day.date} title={`${day.date}: ${day.count} repositories last pushed`} style={{ background: day.count ? p.accent : p.border, opacity: day.count ? Math.min(1, .4 + day.count * .2) : .4 }}/>)}</div><span className="activity-note">{card.data.activityLabel}</span></section>;
 const identity = <><h2>{name}</h2><span className="design-handle">@{profile.login}</span></>;
 return <article id={miniature ? undefined : 'devcard'} data-design={theme} className={`dev-card design-card design-${theme}${miniature ? ' is-miniature' : ''}`} style={{ '--card-bg': p.bg, '--card-text': p.text, '--card-muted': p.muted, '--card-accent': p.accent, '--card-border': p.border } as CSSProperties}>
  {theme === 'anime' && <><header className="anime-masthead"><span>DEVCARD / CHARACTER FILE</span><b>開発者</b></header><div className="anime-cover"><div className="anime-side">THE NEXT ARC STARTS HERE</div><div className="anime-portrait">{avatar}<span>DEV</span></div><div className="anime-name">{identity}<span className="anime-tag">OPEN SOURCE PROTAGONIST</span></div></div><div className="anime-caption">{bio}</div>{metrics}<div className="design-body">{languageSection}{!miniature && repoSection}{!miniature && activitySection}</div></>}
  {theme === 'ai' && <><header className="ai-toolbar"><span>◈ NEURAL PROFILE</span><span className="system-status">PUBLIC DATA</span></header><div className="ai-core"><span className="ai-coordinate">NODE / {profile.id}</span><div className="ai-avatar-ring">{avatar}</div>{identity}{bio}<div className="ai-connector"/></div>{metrics}<div className="design-body">{languageSection}{!miniature && repoSection}{!miniature && activitySection}</div></>}
  {theme === 'alien' && <><div className="alien-security"><span>EXTRATERRESTRIAL ARCHIVE</span><b>FILE {String(profile.id).slice(-5)}</b></div><div className="alien-dossier"><div className="alien-scan">{avatar}<span>SPECIMEN / DEV</span></div><div className="alien-identity"><span className="alien-class">CLASSIFICATION: BUILDER</span>{identity}<dl><div><dt>ORIGIN</dt><dd>{profile.location || 'Undisclosed'}</dd></div><div><dt>FREQUENCY</dt><dd>github.com</dd></div></dl></div></div><div className="alien-transmission"><span>TRANSMISSION_001</span>{bio}</div>{metrics}<div className="design-body">{languageSection}{!miniature && repoSection}{!miniature && activitySection}</div></>}
  {theme === 'superhero' && <><header className="comic-masthead"><b>THE INCREDIBLE DEVELOPER</b><span>ISSUE #{String(profile.id).slice(-3)}</span></header><div className="comic-cover"><div className="comic-portrait">{avatar}<span>CODE!</span></div><div className="comic-identity"><span>MEET YOUR HERO</span>{identity}</div></div><div className="comic-speech">{bio}</div>{metrics}<div className="design-body">{languageSection}{!miniature && repoSection}{!miniature && activitySection}</div></>}
  {theme === 'coder' && <><header className="editor-title"><span className="window-dots"><i/><i/><i/></span><span>{profile.login} — devcard</span><span>⌘</span></header><div className="editor-tabs"><span><b>TS</b> developer.ts <em>×</em></span><span>README.md</span></div><div className="coder-layout"><div className="coder-rail"><span>▤</span><span>⌕</span><span>⑂</span><span>⚙</span></div><div className="coder-source"><div className="coder-profile">{avatar}<div>{identity}</div></div><div className="code-line"><span>01</span><code><i>export const</i> developer = {'{'}</code></div><div className="code-line"><span>02</span><code> username: <b>{JSON.stringify(profile.login)}</b>,</code></div><div className="code-line"><span>03</span><code> bio: <b>{JSON.stringify(profile.bio || 'Building in the open.')}</b>,</code></div><div className="code-line"><span>04</span><code> stack: <b>[{languages.slice(0, 3).map(l => JSON.stringify(l.name)).join(', ')}]</b></code></div><div className="code-line"><span>05</span><code>{'};'}</code></div>{metrics}{languageSection}{!miniature && repoSection}{!miniature && activitySection}</div></div><div className="coder-status"><span>⑂ main*</span><span>TypeScript · UTF-8 · DevCard</span></div></>}
  {theme === 'linux' && <><header className="linux-title"><span className="window-dots"><i/><i/><i/></span><span>{profile.login}@devcard: ~</span><span>— □ ×</span></header><div className="linux-content"><div className="shell-command"><b>{profile.login}@devcard</b><span>:~$</span> fastfetch --github</div><div className="linux-fetch"><div className="linux-avatar">{avatar}<span>[ public profile ]</span></div><div className="linux-info"><h2>{profile.login}<span>@</span>github</h2><div className="linux-rule">──────────────────</div><dl><div><dt>Name</dt><dd>{name}</dd></div><div><dt>Host</dt><dd>GitHub</dd></div><div><dt>Location</dt><dd>{profile.location || 'Earth'}</dd></div><div><dt>Shell</dt><dd>{languages[0]?.name || 'Code'}</dd></div>{stats.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{compact(value)}</dd></div>)}</dl><div className="ansi-colors">{['#eb6f92','#f6c177','#9ccfd8','#c4a7e7','#31748f','#ebbcba','#e0def4','#908caa'].map(color => <span key={color} style={{ background: color }}/>)}</div></div></div><div className="shell-command"><b>❯</b> cat about.txt</div>{bio}{languageSection}{!miniature && repoSection}{!miniature && activitySection}<div className="shell-command linux-prompt"><b>❯</b><span className="cursor-block"/></div></div></>}
  {!miniature && <footer className="design-footer"><span>DEVCARD / {theme.toUpperCase()} EDITION</span><a href={profile.html_url} target="_blank" rel="noreferrer">github.com/{profile.login} ↗</a></footer>}
 </article>;
}
